name: Build Windows WPF Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish Windows application
      run: |
        dotnet publish SpineViewerWPF.csproj -c Release -o ./publish --runtime win-x64
        Compress-Archive -Path ./publish/* -DestinationPath "./SpineViewerWPF-win-x64.zip"
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SpineViewerWPF
        path: ./SpineViewerWPF-win-x64.zip
