name: Build and Package Windows .NET 8 Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  DOTNET_VERSION: '8.0.x'
  CONFIGURATION: 'Release'
  OUTPUT_DIR: 'build-output'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build for Windows (x64)
      run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Create output directory
      run: |
        New-Item -Path ${{ env.OUTPUT_DIR }} -ItemType Directory -Force
        Copy-Item -Path "**/bin/${{ env.CONFIGURATION }}/**/*" -Destination ${{ env.OUTPUT_DIR }} -Recurse -Force

    - name: Compress build output
      run: |
        $date = Get-Date -Format "yyyyMMdd"
        Compress-Archive -Path "${{ env.OUTPUT_DIR }}/*" -DestinationPath "./BuildOutput-$date.zip"

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Build-Output
        path: ./BuildOutput-*.zip
